### ISSUE TITLE
Correct formatting in import

### ISSUE THREAD

**Issue by marcuzz0** [bmr-cymru/csv2kml#9]
Hi,
how do I set up the formatting?
I have a file with the following columns:
Name, Lat, Lon, Hei

**Comment by aseedig** [comment]
Hi,

This script was designed to work with DJI Drone Logfiles, which were converted into CSV files. You cannot just put any CSV file not containing the relevant columns into this script. Additional fields were then injected to these CSV files.

Name, Lat, Lon and Hei (I assume this is altitude) are not enough. Other columns are still needed.
You need a proper date/time stamp for each location point, a Tick-Number field (which in DJI files represents the milliseconds since the logfile was started on the drone). 
You also need The Flight-State of the drone per location, a base location in Lat, Lon & Alt, a polygone location for a virtual geofence etc. If you have a look at the source code, you will find header map sections where the fields are described based on which mode you are going to use.

This script was a special development to show a flight path of a DJI drone within a geofence location in relation to the base station (Pilot Location). 

Maybe you could tell us what exactly you're trying to do? This script might not be suitable for what you're trying to achieve.

Have a great day

Axel

**Comment by bmr-cymru** [comment]
What data are you trying to use as input? As @aseedig said, the script was designed to work with CSV data from DJI's drones and is fairly specific to that format. It might still be possible for you to get things to work with some effort - I don't recall off hand exactly what the minimum set of data required is, but the script is fairly simple and adaptable.

**Comment by marcuzz0** [comment]
hello everyone very kind for the quick answers ...

I need a script that takes the coordinates of a csv file and transforms them into kml.
I found this that seems to fit me well:
https://github.com/Thierry46/table2kml

Thanks to both a greeting
Marco
